StartupEvents.registry("block", (event) => {
	/**
	 * 
	 * @param {String} name 注册id
	 * @param 
	 */
	function addBlock(name, type) {
		if (type === undefined) {
			return event.create(`${global.namespace}:${name}`)
		}
		return event.create(`${global.namespace}:${name}`, type)
	}

	// 虚空涌泉
	addBlock("void_spring")
		.hardness(-1)
		.resistance(114514)

	// 冲击桩
	addBlock("impact_pile")
		.model(`${global.namespace}:block/custom/impact_pile`)
		.defaultCutout()
		.soundType(SoundType.NETHERITE_BLOCK)
		.box(7, 0, 7, 9, 14, 9, true)
		.box(6, 14, 6, 10, 16, 10, true)
		.hardness(5)
		.resistance(5)

	// 破旧的存钱罐
	addBlock("piggy_bank", "cardinal")
		.soundType(SoundType.DECORATED_POT)
		.waterlogged()
		.notSolid()
		.defaultCutout()
		.box(9.75, 0, 12, 11.75, 2, 14)
		.box(5.25, 0, 12, 7.25, 2, 14)
		.box(9.75, 0, 5, 11.75, 2, 7)
		.box(9, 5.5, 12.25, 10, 7.5, 14.25)
		.box(8.13281, 8.00781, 7.75, 8.88281, 8.00781, 12.75)
		.box(5.24219, 2.75, 8.5, 5.24219, 7.5, 11.5)
		.box(11.75781, 2.75, 8.5, 11.75781, 7.5, 11.5)
		.box(5.25, 2, 5, 11.75, 8, 14)
		.box(5.25, 0, 5, 7.25, 2, 7)
		.box(5, 3.75, 0.75, 12, 9.75, 6.75)
		.box(7, 5.5, 0, 10, 7.5, 1)

	// 背景
	addBlock("green_screen")
		.lightLevel(15)

	// 锇砖瓦
	addBlock("osmium_tile")
		.soundType(SoundType.METAL)
		.hardness(6)
		.resistance(6)
		.tagBlock(global.ToolType["pickaxe"])
		.tagBlock(global.MiningLevel["iron"])
		.requiresTool(true)

	// 泥炭
	addBlock("peat_block")
		.soundType(SoundType.MUD)
		.hardness(1)
		.resistance(1)
		.tagBlock(global.ToolType["shovel"])
		.tagBlock(global.MiningLevel["wooden"])
		.tagBlock("minecraft:dirt")
		.tag("minecraft:stone")

	// 油页岩
	addBlock("oil_shale")
		.soundType(SoundType.DEEPSLATE)
		.hardness(15)
		.resistance(15)
		.tagBlock(global.MiningLevel["nether"])
		.tagBlock(global.ToolType["pickaxe"])
		.requiresTool(true)

	// 压缩末地粉块
	addBlock("compression_end_stone_dust_block")
		.soundType(SoundType.SAND)
		.hardness(6)
		.resistance(6)
		.tagBlock(global.ToolType["pickaxe"])
		.tagBlock(global.MiningLevel["wooden"])
		.requiresTool(true)

	// 坩埚底座
	addBlock("crucible_base")
		.textureAll(`${global.namespace}:block/crucible/top`)
		.soundType(SoundType.METAL)
		.hardness(6)
		.resistance(6)
		.tagBlock(global.ToolType["pickaxe"])
		.tagBlock(global.MiningLevel["iron"])
		.requiresTool(true)

	// 坩埚风口
	addBlock("crucible_tuyere")
		.soundType(SoundType.METAL)
		.hardness(6)
		.resistance(6)
		.tagBlock(global.ToolType["pickaxe"])
		.tagBlock(global.MiningLevel["iron"])
		.requiresTool(true)

	// 青铜外壳
	addBlock("bronze_casing")
		.textureAll(`${global.namespace}:block/casing/bronze/casing`)
		.soundType(SoundType.WOOD)
		.hardness(5)
		.resistance(5)
		.tagBlock(global.ToolType["pickaxe"])
		.tagBlock(global.WRENCH_PICKUP)

	// 陨石外壳
	addBlock("smart_casing")
		.textureAll(`${global.namespace}:block/casing/ae2/smart`)
		.soundType(SoundType.METAL)
		.hardness(5)
		.resistance(5)
		.tagBlock(global.ToolType["pickaxe"])
		.tagBlock(global.WRENCH_PICKUP)

	// 高级计算外壳
	addBlock("computing_casing")
		.model(`${global.namespace}:block/casing/ae2/computing`)
		.soundType(SoundType.METAL)
		.hardness(5)
		.resistance(5)
		.tagBlock(global.ToolType["pickaxe"])
		.tagBlock(global.WRENCH_PICKUP)

	// 辐射沙
	addBlock("radsand", "falling")
		.textureAll(`${global.namespace}:block/radsand`)
		.soundType(SoundType.SAND)
		.hardness(0.5)
		.resistance(0.5)
		.tagBlock("minecraft:sand")
		.tagBlock(global.ToolType["shovel"])

	// 破损钻头
	addBlock("broken_andesite_drill_head")
		.model(`${global.namespace}:block/drill/broken_andesite_drill_head`)
		.soundType(SoundType.STONE)
		.hardness(3)
		.resistance(3)
		.box(2, 1, 2, 14, 3, 14, true)
		.box(3, 3, 3, 13, 6, 13, true)
		.box(4, 6, 4, 12, 9, 12, true)
		.box(5, 9, 5, 11, 12, 11, true)
		.box(6, 12, 6, 10, 15, 10, true)
		.box(7, 15, 7, 9, 18, 9, true)
		.box(6, 1, 1, 10, 7, 3, true)
		.box(6, 1, 13, 10, 7, 15, true)
		.box(13, 1, 6, 15, 7, 10, true)
		.box(1, 1, 6, 3, 7, 10, true)
		.box(4, 0, 4, 12, 1, 6, true)
		.box(4, 0, 10, 12, 1, 12, true)
		.box(10, 0, 6, 12, 1, 10, true)
		.box(4, 0, 6, 6, 1, 10, true)
		.requiresTool()
		.notSolid()
		.tagBlock(global.MiningLevel["wooden"])
		.tagBlock(global.ToolType["pickaxe"])
		.tagBlock(global.WRENCH_PICKUP)
		.tag(`${global.namespace}:broken_drill_heads`)

	addBlock("broken_copper_drill_head")
		.model(`${global.namespace}:block/drill/broken_copper_drill_head`)
		.soundType(SoundType.METAL)
		.hardness(3)
		.resistance(3)
		.box(2, 1, 2, 14, 3, 14, true)
		.box(3, 3, 3, 13, 6, 13, true)
		.box(4, 6, 4, 12, 9, 12, true)
		.box(5, 9, 5, 11, 12, 11, true)
		.box(6, 12, 6, 10, 15, 10, true)
		.box(7, 15, 7, 9, 18, 9, true)
		.box(6, 1, 1, 10, 7, 3, true)
		.box(6, 1, 13, 10, 7, 15, true)
		.box(13, 1, 6, 15, 7, 10, true)
		.box(1, 1, 6, 3, 7, 10, true)
		.box(4, 0, 4, 12, 1, 6, true)
		.box(4, 0, 10, 12, 1, 12, true)
		.box(10, 0, 6, 12, 1, 10, true)
		.box(4, 0, 6, 6, 1, 10, true)
		.requiresTool()
		.notSolid()
		.tagBlock(global.MiningLevel["stone"])
		.tagBlock(global.ToolType["pickaxe"])
		.tagBlock(global.WRENCH_PICKUP)
		.tag(`${global.namespace}:broken_drill_heads`)

	addBlock("broken_brass_drill_head")
		.model(`${global.namespace}:block/drill/broken_brass_drill_head`)
		.soundType(SoundType.METAL)
		.hardness(4)
		.resistance(3)
		.box(2, 1, 2, 14, 3, 14, true)
		.box(3, 3, 3, 13, 6, 13, true)
		.box(4, 6, 4, 12, 9, 12, true)
		.box(5, 9, 5, 11, 12, 11, true)
		.box(6, 12, 6, 10, 15, 10, true)
		.box(7, 15, 7, 9, 18, 9, true)
		.box(6, 1, 1, 10, 7, 3, true)
		.box(6, 1, 13, 10, 7, 15, true)
		.box(13, 1, 6, 15, 7, 10, true)
		.box(1, 1, 6, 3, 7, 10, true)
		.box(4, 0, 4, 12, 1, 6, true)
		.box(4, 0, 10, 12, 1, 12, true)
		.box(10, 0, 6, 12, 1, 10, true)
		.box(4, 0, 6, 6, 1, 10, true)
		.requiresTool()
		.notSolid()
		.tagBlock(global.MiningLevel["stone"])
		.tagBlock(global.ToolType["pickaxe"])
		.tagBlock(global.WRENCH_PICKUP)
		.tag(`${global.namespace}:broken_drill_heads`)

	// // 耐压外壳
	// addBlock("pressure_resistance_casing")
	// 	.textureAll(`${global.namespace}:block/casing/pressure_resistance/casing`)
	// 	.soundType(SoundType.NETHERITE_BLOCK)
	// 	.hardness(5)
	// 	.resistance(5)
	// 	.tagBlock(global.ToolType["pickaxe"])
	// 	.tagBlock(global.WRENCH_PICKUP)
})