StartupEvents.registry("block", (event) => {
	CmiGlobal.mechanismGroup.forEach((type) => {
		event.create(`${CmiCore.MODID}:${type}_machine`, "cardinal")
			.soundType(SoundType.METAL)
			.waterlogged()
			.model(`${CmiCore.MODID}:block/machine_block/${type}`)
			.requiresTool(true)
			.notSolid()
			.defaultCutout()
			.blockEntity((entity) => {
				let mechanism = Ingredient.of(`#create:mechanisms/${type}`)
				let flashDrive = Ingredient.of(`#${CmiCore.MODID}:mechanism_flash_drives/${type}`)

				entity.enableSync()
				entity.inventory(9, 3, [mechanism, flashDrive])
				entity.rightClickOpensInventory()
				entity.attachCapability(attachItemHandlerCapability())
			})
			.tagBlock(CmiToolType.PICKAXE)
			.tagBlock(CmiMiningLevel.WOODEN)
			.tagBlock(CmiGlobal.WRENCH_PICKUP)
			.tag("cmi:machine_block")
			.tag(`cmi:machine_block/${type}`)
	})
})