// Ponder.registry((event) => {
// 	event.create("ae2:me_p2p_tunnel")
// 		.scene("ae2:p2p_tunnel", "P2P tunnels", "cmi:ae2/p2p_tunnels", (scene) => {
// 			scene.showBasePlate()
// 			scene.idle(20)

// 			scene.world().showSection([1, 1, 2, 3, 1, 2], Direction.DOWN)
// 			scene.world().setBlocks([2, 3, 2, 2, 7, 2], "minecraft:air", false)
// 			scene.idle(20)


// 			// ME P2P通道是利用ME网络传输另一个ME网络频道的设备
// 			scene.text(60, "Me P2P Tunnels are devices to transmit channels via another ME network", [3.5, 1.5, 2.5])
// 			scene.idle(80)

// 			// P2P即“点对点”, P2P通道的两端等效于设备直接接触
// 			scene.text(80, "P2P stands for Point to Point, edges of P2P Tunnels shows no difference from direct connection", [1.5, 1.5, 2.5])
// 			scene.idle(100)
// 			scene.addKeyframe()

// 			// P2P通道需要使用内存卡设置连接
// 			scene.text(60, "P2P Tunnels need to set connections with a Memory Card")
// 			scene.showControls(20, [3.5, 2, 2], "down")
// 				.rightClick()
// 				.whileSneaking()
// 				.withItem("ae2:memory_card")
// 			scene.idle(30)
// 			scene.showControls(20, [1, 2, 2.5], "down")
// 				.rightClick()
// 				.withItem("ae2:memory_card")
// 			scene.idle(50)

// 			// 这样就可以通过它们传输频道了！
// 			scene.text(60, "And now channels can go through P2P Tunnels!", [3.5, 1.5, 1.5])
// 			scene.world().setBlocks([0, 1, 2], "ae2:drive")
// 			scene.world().showSection([0, 1, 2], Direction.DOWN)
// 			scene.world().setBlocks([3, 1, 1], "ae2:controller")
// 			scene.world().showSection([3, 1, 1], Direction.DOWN)
// 			scene.idle(80)
// 			scene.addKeyframe()

// 			// P2P通道是单向传输的, 但是支持多个输出
// 			scene.text(60, "P2P tunnel provides only one-way transmission, but it supports multiple outputs")
// 			scene.world().showSection([2, 2, 2], Direction.DOWN)
// 			scene.idle(20)
// 			scene.showControls(40, [2.5, 3, 2.5], "down")
// 				.rightClick()
// 				.withItem("ae2:memory_card")
// 			scene.idle(60)

// 			// 但是注意, 每个P2P通道都将消耗一个频道
// 			scene.text(60, "But attention! Every one of P2P Tunnel will consume 1 channel!")
// 			scene.idle(80)
// 			scene.addKeyframe()

// 			// 使用红石或红石块右键P2P通道将其变为红石P2P通道
// 			scene.text(80, "Rightclick the tunnel with a Redstone or a Redstone Block to transform it into a Redstone P2P Tunnel")
// 			scene.world().hideSection([2, 2, 2], Direction.UP)
// 			scene.world().hideSection([0, 1, 2], Direction.UP)
// 			scene.world().hideSection([3, 1, 1], Direction.UP)
// 			scene.idle(20)
// 			scene.showControls(40, [3.5, 2, 2], "down")
// 				.rightClick()
// 				.withItem("minecraft:redstone")
// 			scene.showControls(40, [1, 2, 2.5], "down")
// 				.rightClick()
// 				.withItem("minecraft:redstone_block")
// 			scene.world().setBlocks([1, 1, 2], "minecraft:air", false)
// 			scene.world().setBlocks([3, 1, 2], "minecraft:air", false)
// 			let redStoneSection = scene.world().showIndependentSectionImmediately([1, 3, 2, 3, 3, 2])
// 			scene.world().moveSection(redStoneSection, [0, -2, 0], 0)
// 			scene.idle(20)
// 			scene.world().setBlocks([0, 1, 2], "minecraft:redstone_lamp", false)
// 			scene.world().showSection([0, 1, 2], Direction.DOWN)
// 			scene.world().setBlocks([3, 1, 1], "minecraft:redstone_block", false)
// 			scene.world().showSection([3, 1, 1], Direction.DOWN)
// 			scene.idle(20)
// 			scene.world().modifyBlock([0, 1, 2], (state) => state.with("lit", "true"), false)
// 			scene.idle(60)
// 			scene.addKeyframe()

// 			// 使用箱子或漏斗右键P2P通道将其变为物品P2P通道
// 			scene.text(80, "Rightclick the tunnel with a Chest or a Hopper to transform it into an Item P2P Tunnel")
// 			scene.world().hideSection([0, 1, 2], Direction.UP)
// 			scene.world().hideSection([3, 1, 1], Direction.UP)
// 			scene.idle(20)
// 			scene.showControls(40, [3.5, 2, 2], "down")
// 				.rightClick()
// 				.withItem("minecraft:chest")
// 			scene.showControls(40, [1, 2, 2.5], "down")
// 				.rightClick()
// 				.withItem("minecraft:hopper")
// 			scene.world().setBlocks([1, 3, 2, 3, 3, 2], "minecraft:air", false)
// 			scene.world().hideIndependentSection(redStoneSection, Direction.UP)
// 			let itemSection = scene.world().showIndependentSectionImmediately([1, 4, 2, 3, 4, 2])
// 			scene.world().moveSection(itemSection, [0, -3, 0], 0)
// 			scene.idle(20)
// 			scene.world().setBlocks([0, 1, 2], "minecraft:barrel", false)
// 			scene.world().showSection([0, 1, 2], Direction.DOWN)
// 			scene.world().setBlocks([3, 1, 1], "minecraft:hopper", false)
// 			scene.world().modifyBlock([3, 1, 1], (state) => state.with("facing", "south"), false)
// 			scene.world().showSection([3, 1, 1], Direction.DOWN)
// 			scene.idle(20)
// 			scene.showControls(20, [3.5, 2, 1.5], "down")
// 				.withItem("minecraft:diamond")
// 			scene.idle(20)
// 			scene.showControls(20, [0.5, 2, 2.5], "down")
// 				.withItem("minecraft:diamond")
// 			scene.idle(20)
// 			scene.addKeyframe()

// 			// 使用任意流体桶右键P2P通道将其变为流体P2P通道
// 			scene.text(80, "Rightclick the tunnel with a fluid bucket to transform it into a Fluid P2P Tunnel")
// 			scene.world().hideSection([0, 1, 2], Direction.UP)
// 			scene.world().hideSection([3, 1, 1], Direction.UP)
// 			scene.idle(20)
// 			scene.showControls(40, [3.5, 2, 2], "down")
// 				.rightClick()
// 				.withItem("minecraft:bucket")
// 			scene.showControls(40, [1, 2, 2.5], "down")
// 				.rightClick()
// 				.withItem("minecraft:lava_bucket")
// 			scene.world().setBlocks([1, 4, 2, 3, 4, 2], "minecraft:air", false)
// 			scene.world().hideIndependentSection(itemSection, Direction.UP)
// 			scene.world().modifyBlock([3, 1, 3], (state) => state.with("shape", "plain"), false)
// 			let fluidSection = scene.world().showIndependentSectionImmediately([1, 5, 2, 3, 5, 2])
// 			scene.world().moveSection(fluidSection, [0, -4, 0], 0)
// 			scene.idle(20)
// 			let pumpSection = scene.world().showIndependentSection([3, 1, 3, 4, 2, 4], Direction.DOWN)
// 			scene.world().moveSection(pumpSection, [0, 0, -3], 0)
// 			scene.world().setBlocks([0, 1, 2], "create:fluid_tank", false)
// 			scene.world().modifyBlock([0, 1, 2], (state) => state.with("shape", "plain"), false)
// 			scene.world().showSection([0, 1, 2], Direction.DOWN)
// 			scene.idle(60)
// 			scene.addKeyframe()

// 			// 用能源元件或能源接收器右键P2P通道来将其变为能量P2P通道
// 			scene.text(80, "Rightclick the tunnel with an Energy Call or an Energy Acceptor to transform it into an Energy P2P Tunnel")
// 			scene.world().hideSection([0, 1, 2], Direction.UP)
// 			scene.world().hideIndependentSection(pumpSection, Direction.UP)
// 			scene.idle(20)
// 			scene.showControls(40, [3.5, 2, 2], "down")
// 				.rightClick()
// 				.withItem("ae2:energy_acceptor")
// 			scene.showControls(40, [1, 2, 2.5], "down")
// 				.rightClick()
// 				.withItem("ae2:energy_cell")
// 			scene.world().setBlocks([1, 5, 2, 3, 5, 2], "minecraft:air", false)
// 			scene.world().hideIndependentSection(fluidSection,Direction.UP)
// 			let energySection = scene.world().showIndependentSectionImmediately([1, 6, 2, 3, 6, 2])
// 			scene.world().moveSection(energySection, [0, -5, 0], 0)
// 			scene.idle(40)
// 			scene.world().setBlocks([0, 1, 2], "ae2:controller", false)
// 			scene.world().showSection([0, 1, 2], Direction.DOWN)
// 			scene.world().setBlocks([3, 1, 1], "createaddition:creative_energy", false)
// 			scene.world().showSection([3, 1, 1], Direction.DOWN)
// 			scene.idle(20)
// 			scene.world().modifyBlock([0, 1, 2], (state) => state.with("state", "online"), false)
// 			scene.idle(40)
// 			scene.addKeyframe()

// 			// 而使用萤石右键P2P通道可以把它变成光P2P通道
// 			scene.text(40, "Rightclick the tunnel with a Glowstone to transform it into a Light P2P Tunnel")
// 			scene.world().hideSection([0, 1, 2], Direction.UP)
// 			scene.world().hideSection([3, 1, 1], Direction.UP)
// 			scene.idle(20)
// 			scene.showControls(40, [3.5, 2, 2], "down")
// 				.rightClick()
// 				.withItem("minecraft:glowstone")
// 			scene.showControls(40, [1, 2, 2.5], "down")
// 				.rightClick()
// 				.withItem("minecraft:glowstone")
// 			scene.world().setBlocks([1, 6, 2, 3, 6, 2], "minecraft:air", false)
// 			scene.world().hideIndependentSection(energySection,Direction.UP)
// 			let lightSection = scene.world().showIndependentSectionImmediately([1, 7, 2, 3, 7, 2])
// 			scene.world().moveSection(lightSection, [0, -6, 0], 0)
// 			scene.idle(40)

// 			// 是的, 它只传播光照
// 			scene.text(40, "Yeah, it transmits only light", [1, 2, 2.5])
// 			scene.world().setBlocks([3, 1, 1], "minecraft:glowstone", false)
// 			scene.world().showSection([3, 1, 1], Direction.DOWN)
// 			scene.idle(20)
// 			scene.showControls(20, [1, 2, 2.5], "down")
// 				.withItem("minecraft:light")
// 			scene.idle(40)

// 			// (￣△￣；)
// 			scene.text(20, ":/", [1, 2, 2.5])
// 			scene.idle(40)

// 			// 真奇怪╮(￣▽￣)╭
// 			scene.text(20, "Weird:P", [1, 2, 2, 5])
// 			scene.idle(40)
// 		})
// })