ServerEvents.recipes((event) => {
	let { mekanism } = event.recipes

	mekanism.rotary()
		.fluidInput(Fluid.of(IngrUtils.getFirstFluidId("forge:brine"), 200))
		.fluidOutput(Fluid.of(IngrUtils.getFirstFluidId("forge:brine"), 200))
		.gasInput(MekanismType.Gas.of("mekanism:brine", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:brine", 200))
		.id("mekanism:rotary/brine")

	mekanism.rotary()
		.fluidInput(Fluid.of(IngrUtils.getFirstFluidId("forge:chlorine"), 200))
		.fluidOutput(Fluid.of(IngrUtils.getFirstFluidId("forge:chlorine"), 200))
		.gasInput(MekanismType.Gas.of("mekanism:chlorine", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:chlorine", 200))
		.id("mekanism:rotary/chlorine")

	mekanism.rotary()
		.fluidInput(Fluid.of(IngrUtils.getFirstFluidId("forge:ethene"), 200))
		.fluidOutput(Fluid.of(IngrUtils.getFirstFluidId("forge:ethene"), 200))
		.gasInput(MekanismType.Gas.of("mekanism:ethene", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:ethene", 200))
		.id("mekanism:rotary/ethene")

	mekanism.rotary()
		.fluidInput(Fluid.of(IngrUtils.getFirstFluidId("forge:hydrofluoric_acid"), 200))
		.fluidOutput(Fluid.of(IngrUtils.getFirstFluidId("forge:hydrofluoric_acid"), 200))
		.gasInput(MekanismType.Gas.of("mekanism:hydrofluoric_acid", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:hydrofluoric_acid", 200))
		.id("mekanism:rotary/hydrofluoric_acid")

	mekanism.rotary()
		.fluidInput(Fluid.of(IngrUtils.getFirstFluidId("forge:hydrogen_chloride"), 200))
		.fluidOutput(Fluid.of(IngrUtils.getFirstFluidId("forge:hydrogen_chloride"), 200))
		.gasInput(MekanismType.Gas.of("mekanism:hydrogen_chloride", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:hydrogen_chloride", 200))
		.id("mekanism:rotary/hydrogen_chloride")

	mekanism.rotary()
		.fluidInput(Fluid.of(IngrUtils.getFirstFluidId("forge:hydrogen"), 200))
		.fluidOutput(Fluid.of(IngrUtils.getFirstFluidId("forge:hydrogen"), 200))
		.gasInput(MekanismType.Gas.of("mekanism:hydrogen", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:hydrogen", 200))
		.id("mekanism:rotary/hydrogen")

	mekanism.rotary()
		.fluidInput(Fluid.of(IngrUtils.getFirstFluidId("forge:lithium"), 200))
		.fluidOutput(Fluid.of(IngrUtils.getFirstFluidId("forge:lithium"), 200))
		.gasInput(MekanismType.Gas.of("mekanism:lithium", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:lithium", 200))
		.id("mekanism:rotary/lithium")

	mekanism.rotary()
		.fluidInput(Fluid.of(IngrUtils.getFirstFluidId("forge:oxygen"), 200))
		.fluidOutput(Fluid.of(IngrUtils.getFirstFluidId("forge:oxygen"), 200))
		.gasInput(MekanismType.Gas.of("mekanism:oxygen", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:oxygen", 200))
		.id("mekanism:rotary/oxygen")

	mekanism.rotary()
		.fluidInput(Fluid.of(IngrUtils.getFirstFluidId("forge:sodium"), 200))
		.fluidOutput(Fluid.of(IngrUtils.getFirstFluidId("forge:sodium"), 200))
		.gasInput(MekanismType.Gas.of("mekanism:sodium", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:sodium", 200))
		.id("mekanism:rotary/sodium")

	mekanism.rotary()
		.fluidInput(Fluid.of(IngrUtils.getFirstFluidId("forge:steam"), 200))
		.fluidOutput(Fluid.of(IngrUtils.getFirstFluidId("forge:steam"), 200))
		.gasInput(MekanismType.Gas.of("mekanism:steam", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:steam", 200))
		.id("mekanism:rotary/steam")

	mekanism.rotary()
		.fluidInput(Fluid.of(IngrUtils.getFirstFluidId("forge:sulfur_dioxide"), 200))
		.fluidOutput(Fluid.of(IngrUtils.getFirstFluidId("forge:sulfur_dioxide"), 200))
		.gasInput(MekanismType.Gas.of("mekanism:sulfur_dioxide", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:sulfur_dioxide", 200))
		.id("mekanism:rotary/sulfur_dioxide")

	mekanism.rotary()
		.fluidInput(Fluid.of(IngrUtils.getFirstFluidId("forge:sulfur_trioxide"), 200))
		.fluidOutput(Fluid.of(IngrUtils.getFirstFluidId("forge:sulfur_trioxide"), 200))
		.gasInput(MekanismType.Gas.of("mekanism:sulfur_trioxide", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:sulfur_trioxide", 200))
		.id("mekanism:rotary/sulfur_trioxide")

	mekanism.rotary()
		.fluidInput(Fluid.of("mekanism:sulfric_acid", 200))
		.fluidOutput(Fluid.of("mekanism:sulfric_acid", 200))
		.gasInput(MekanismType.Gas.of("mekanism:sulfuric_acid", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:sulfuric_acid", 200))
		.id("mekanism:rotary/sulfuric_acid")

	mekanism.rotary()
		.fluidInput(Fluid.of(IngrUtils.getFirstFluidId("forge:superheated_sodium"), 200))
		.fluidOutput(Fluid.of(IngrUtils.getFirstFluidId("forge:superheated_sodium"), 200))
		.gasInput(MekanismType.Gas.of("mekanism:superheated_sodium", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:superheated_sodium", 200))
		.id("mekanism:rotary/superheated_sodium")

	mekanism.rotary()
		.fluidInput(Fluid.of(IngrUtils.getFirstFluidId("forge:uranium_hexafluoride"), 200))
		.fluidOutput(Fluid.of(IngrUtils.getFirstFluidId("forge:uranium_hexafluoride"), 200))
		.gasInput(MekanismType.Gas.of("mekanism:uranium_hexafluoride", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:uranium_hexafluoride", 200))
		.id("mekanism:rotary/uranium_hexafluoride")

	mekanism.rotary()
		.fluidInput(Fluid.of(IngrUtils.getFirstFluidId("forge:uranium_oxide"), 200))
		.fluidOutput(Fluid.of(IngrUtils.getFirstFluidId("forge:uranium_oxide"), 200))
		.gasInput(MekanismType.Gas.of("mekanism:uranium_oxide", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:uranium_oxide", 200))
		.id("mekanism:rotary/uranium_oxide")

	mekanism.rotary()
		.fluidInput(Fluid.of(IngrUtils.getFirstFluidId("minecraft:water"), 200))
		.fluidOutput(Fluid.of(IngrUtils.getFirstFluidId("minecraft:water"), 200))
		.gasInput(MekanismType.Gas.of("mekanism:water_vapor", 200))
		.gasOutput(MekanismType.Gas.of("mekanism:water_vapor", 200))
		.id("mekanism:rotary/water")

	mekanism.rotary()
		.fluidInput(Fluid.of("cmi:fluid_nitroglycerine", 200))
		.gasOutput(MekanismType.Gas.of("cmi:nitroglycerine", 20))
		.fluidOutput(Fluid.of("cmi:fluid_nitroglycerine", 200))
		.gasInput(MekanismType.Gas.of("cmi:nitroglycerine", 20))

	mekanism.rotary()
		.fluidInput(Fluid.of("cmi:geyser_jet", 200))
		.gasOutput(MekanismType.Gas.of("cmi:geyser_jet", 200))
		.fluidOutput(Fluid.of("cmi:geyser_jet", 200))
		.gasInput(MekanismType.Gas.of("cmi:geyser_jet", 200))

	mekanism.rotary()
		.fluidInput(Fluid.of("cmi:mercury", 200))
		.gasOutput(MekanismType.Gas.of("cmi:mercury", 200))
		.fluidOutput(Fluid.of("cmi:mercury", 200))
		.gasInput(MekanismType.Gas.of("cmi:mercury", 200))

	mekanism.rotary()
		.fluidInput(Fluid.of("cmi:radon", 200))
		.gasOutput(MekanismType.Gas.of("cmi:radon", 200))
		.fluidOutput(Fluid.of("cmi:radon", 200))
		.gasInput(MekanismType.Gas.of("cmi:radon", 200))

	mekanism.rotary()
		.fluidInput(Fluid.of("cmi:xenon", 200))
		.gasOutput(MekanismType.Gas.of("cmi:xenon", 200))
		.fluidOutput(Fluid.of("cmi:xenon", 200))
		.gasInput(MekanismType.Gas.of("cmi:xenon", 200))
})