ServerEvents.tags("block", (event) => {
	/**
	 * 
	 * @param {Special.BlockTag} tag 
	 * @returns 
	 */
	function removeTagAllId(tag) {
		return event.get(tag)
			.removeAll()
	}

	event.get("cmi:overworld_quartz_ore")
		.add("cmi:quartz_ore")
		.add("cmi:deepslate_quartz_ore")

	event.get("cmi:heat_sources")
		.add("minecraft:lava")
		.add("#farmersdelight:heat_sources")
		.remove("mynethersdelight:magma_cake")

	event.get("minecraft:infiniburn_all")
		.add("forge:storage_blocks/coal")
		.add("forge:storage_blocks/charcoal")

	event.get("forge:ores")
		.add("ad_astra:moon_cheese_ore")

	event.get("forge:ores/cheese")
		.add("ad_astra:moon_cheese_ore")

	event.get("cmi:nether_farmland")
		.add("minecraft:netherrack")
		.add("minecraft:soul_sand")
		.add("minecraft:soul_soil")
		.add("mynethersdelight:resurgent_soil")
		.add("mynethersdelight:resurgent_soil_farmland")

	event.get("thermal:machines")
		.add("thermal_extra:endothermic_dehydrator")
		.add("thermal_extra:nitratic_igniter")
		.add("thermal_extra:fluid_mixer")
		.add("thermal_extra:component_assembly")
		.add("thermal_extra:advanced_refinery")

	event.get("thermal:dynamos")
		.add("thermal_extra:dynamo_frost")

	event.add("thermal:devices")
		.add([
			"thermal_extra:device_harvester",
			"thermal_extra:device_lava_gen",
			"thermal:tinker_bench",
			"thermal:charge_bench",
			"thermal:device_tree_extractor",
			"thermal:device_fisher",
			"thermal:device_composter",
			"thermal:device_water_gen",
			"thermal:device_rock_gen",
			"thermal:energy_cell",
			"thermal:fluid_cell",
			"thermal:device_tree_extractor",
			"thermal:device_fisher",
			"thermal:device_composter",
			"thermal:device_water_gen",
			"thermal:device_rock_gen",
			"thermal:device_collector",
			"thermal:device_xp_condenser",
			"thermal:device_nullifier",
			"thermal:device_potion_diffuser",
			"thermal:machine_frame",
			"thermal:energy_cell_frame",
			"thermal:fluid_cell_frame"
		])

	event.get("create:wrench_pickup")
		.add([
			"#thermal:machines",
			"#thermal:dynamos",
			"#forge:storage_blocks",
			"#thermal:devices",

			"@mm",
			"steampowered",
			"@createdeco",
			"@kaleidoscope_cookery",
			"@farmersdelight",
			"@ftbquests",
			"@immersiveindustry",
			"@functionalstorage",
			"@mynethersdelight",
			"@portality",
			"@sophisticatedbackpacks",
			"@pipez",
			"@rechiseledcreate",

			"ad_astra:steel_cable",
			"ad_astra:desh_cable",
			"ad_astra:desh_fluid_pipe",
			"ad_astra:ostrum_fluid_pipe",
			"ad_astra:launch_pad",
			"ad_astra:cable_duct",
			"ad_astra:fluid_pipe_duct",
			"ad_astra:coal_generator",
			"ad_astra:compressor",
			"ad_astra:etrionic_blast_furnace",
			"ad_astra:nasa_workbench",
			"ad_astra:fuel_refinery",
			"ad_astra:oxygen_loader",
			"ad_astra:solar_panel",
			"ad_astra:water_pump",
			"ad_astra:oxygen_distributor",
			"ad_astra:gravity_normalizer",
			"ad_astra:energizer",
			"ad_astra:cryo_freezer",
			"ad_astra:oxygen_sensor",
			"#ad_astra:globes",

			"immersiveengineering:craftingtable",
			"immersiveengineering:workbench",
			"immersiveengineering:circuit_table",
			"immersiveengineering:gunpowder_barrel",
			"immersiveengineering:wooden_barrel",
			"immersiveengineering:turntable",
			"immersiveengineering:crate",
			"immersiveengineering:reinforced_crate",
			"immersiveengineering:sorter",
			"immersiveengineering:item_batcher",
			"immersiveengineering:fluid_sorter",
			"immersiveengineering:windmill",
			"immersiveengineering:watermill",
			"immersiveengineering:logic_unit",
			"immersiveengineering:razor_wire",
			"immersiveengineering:capacitor_lv",
			"immersiveengineering:capacitor_mv",
			"immersiveengineering:capacitor_hv",
			"immersiveengineering:metal_barrel",
			"immersiveengineering:fluid_pump",
			"immersiveengineering:fluid_placer",
			"immersiveengineering:blastfurnace_preheater",
			"immersiveengineering:furnace_heater",
			"immersiveengineering:dynamo",
			"immersiveengineering:thermoelectric_generator",
			"immersiveengineering:electric_lantern",
			"immersiveengineering:charging_station",
			"immersiveengineering:fluid_pipe",
			"immersiveengineering:sample_drill",
			"immersiveengineering:tesla_coil",
			"immersiveengineering:floodlight",
			"immersiveengineering:turret_chem",
			"immersiveengineering:turret_gun",
			"immersiveengineering:cloche",
			"immersiveengineering:electromagnet",
			"immersiveengineering:coil_lv",
			"immersiveengineering:coil_mv",
			"immersiveengineering:coil_hv",
			"immersiveengineering:rs_engineering",
			"immersiveengineering:heavy_engineering",
			"immersiveengineering:light_engineering",
			"immersiveengineering:generator",
			"immersiveengineering:radiator",
			"immersiveengineering:steel_fence",
			"immersiveengineering:alu_fence",
			"immersiveengineering:steel_post",
			"immersiveengineering:alu_post",
			"immersiveengineering:transformer",
			"immersiveengineering:transformer_hv",
			"immersiveengineering:breaker_switch",
			"immersiveengineering:redstone_breaker",
			"#forge:treated_wood",
			"immersiveengineering:current_transformer",
			"immersiveengineering:connector_redstone",
			"immersiveengineering:connector_probe",
			"immersiveengineering:connector_bundled",
			"immersiveengineering:treated_scaffold",
			"immersiveengineering:treated_fence",
			"immersiveengineering:stairs_treated_wood_horizontal",
			"immersiveengineering:stairs_treated_wood_vertical",
			"immersiveengineering:stairs_treated_wood_packaged",
			"#immersiveengineering:mineable/hammer",
			"#forge:sheetmetals",
			"immersiveengineering:lightning_rod",
			"immersiveengineering:coke_oven",
			"immersiveengineering:blast_furnace",
			"immersiveengineering:advanced_blast_furnace",
			"immersiveengineering:alloy_smelter",
			"immersiveengineering:crusher",
			"immersiveengineering:fermenter",
			"immersiveengineering:diesel_generator",
			"immersiveengineering:metal_press",
			"immersiveengineering:assembler",
			"immersiveengineering:auto_workbench",
			"immersiveengineering:bottling_machine",
			"immersiveengineering:silo",
			"immersiveengineering:tank",
			"immersiveengineering:mixer",
			"immersiveengineering:refinery",
			"immersiveengineering:squeezer",
			"immersiveengineering:bucket_wheel",
			"immersiveengineering:excavator",
			"immersiveengineering:sawmill",
			"immersiveengineering:arc_furnace",

			"#cmi:tables",
			"#tconstruct:tables",
			"tconstruct:seared_melter",
			"tconstruct:seared_heater",
			"tconstruct:scorched_alloyer",
			"tconstruct:smeltery_controller",
			"tconstruct:foundry_controller",
			"tconstruct:seared_drain",
			"tconstruct:seared_duct",
			"tconstruct:seared_chute",
			"tconstruct:scorched_drain",
			"tconstruct:scorched_duct",
			"tconstruct:scorched_chute",
			"tconstruct:seared_fuel_tank",
			"tconstruct:seared_fuel_gauge",
			"tconstruct:seared_ingot_tank",
			"tconstruct:seared_ingot_gauge",
			"tconstruct:scorched_fuel_tank",
			"tconstruct:scorched_fuel_gauge",
			"tconstruct:scorched_ingot_tank",
			"tconstruct:scorched_duct",
			"tconstruct:scorched_chute",
			"tconstruct:seared_fuel_tank",
			"tconstruct:seared_fuel_gauge",
			"tconstruct:seared_ingot_tank",
			"tconstruct:seared_ingot_gauge",
			"tconstruct:scorched_fuel_tank",
			"tconstruct:scorched_fuel_gauge",
			"tconstruct:scorched_ingot_tank",
			"tconstruct:seared_basin",
			"tconstruct:scorched_basin",
			"tconstruct:seared_casting_tank",
			"tconstruct:scorched_proxy_tank",
			"tconstruct:seared_fluid_cannon",
			"tconstruct:scorched_fluid_cannon",
			"tconstruct:seared_bricks",
			"tconstruct:scorched_bricks",
			"tconstruct:seared_glass",
			"tconstruct:scorched_glass"
		])
})