// Ponder.registry((event) => {
// 	event.create([
// 		"mekanismgenerators:fission_reactor_casing",
// 		"mekanismgenerators:fission_reactor_port",
// 		"mekanismgenerators:fission_fuel_assembly", "mekanismgenerators:control_rod_assembly",
// 		"mekanismgenerators:fission_reactor_logic_adapter"
// 	]).scene("cmi:fission_reactor", "裂变反应堆", "cmi:other/fission_reactor", (scene) => {
// 		scene.scaleSceneView(0.5)
// 		scene.showStructure(0)
// 		scene.idle(25)
// 		scene.addKeyframe()
// 		let showSection3 = scene.world().showIndependentSection([2, 2, 2, 5, 5, 5], Direction.DOWN)
// 		scene.world().showSection([1, 1, 1, 5, 1, 5], Direction.DOWN)
// 		scene.world().showSection([1, 1, 1, 1, 5, 5], Direction.DOWN)
// 		scene.world().showSection([1, 1, 1, 5, 5, 1], Direction.DOWN)
// 		scene.idle(15)
// 		scene.text(70, "使用裂变反应堆外壳搭建一个长3~18格、宽3~18格、高4~18格的长方体框架")
// 		scene.idle(80)
// 		let showSection = scene.world().showIndependentSection([1, 6, 1, 5, 10, 5], Direction.DOWN)
// 		scene.world().moveSection(showSection, [0, - 5, 0], 0)
// 		scene.addKeyframe()
// 		scene.text(70, "再用强化玻璃或裂变反应堆外壳填满多面体的每一个面")
// 		scene.idle(85)
// 		scene.addKeyframe()
// 		let showSection2 = scene.world().showIndependentSection([1, 11, 1, 5, 12, 5], Direction.DOWN)
// 		scene.world().moveSection(showSection2, [0, - 9, 0], 0)
// 		scene.text(70, "把部分面上的外壳替换为裂变反应堆端口")
// 		scene.idle(85)
// 		scene.addKeyframe()
// 		scene.showControls(50, [2, 3, 1], "left")
// 			.rightClick()
// 			.withItem("mekanism:configurator")
// 			.whileSneaking()
// 		scene.text(50, "潜行时使用配置器右键端口更改输入/输出模式")
// 		scene.idle(65)
// 		scene.world().modifyBlock([2, 11, 1], (state) => state.with("mode", "output_waste"), false)
// 		scene.world().modifyBlock([2, 12, 1], (state) => state.with("mode", "output_coolant"), false)
// 		scene.idle(17)
// 		scene.rotateCameraY(180)
// 		scene.idle(20)
// 		scene.world().hideIndependentSection(showSection3, Direction.UP)
// 		scene.world().moveSection(showSection, [0, 35, 0], 35)
// 		scene.addKeyframe()
// 		scene.world().setBlocks([3, 2, 3], "mekanismgenerators:fission_fuel_assembly")
// 		scene.world().setBlocks([3, 3, 3], "mekanismgenerators:fission_fuel_assembly")
// 		scene.world().setBlocks([3, 4, 3], "mekanismgenerators:control_rod_assembly")
// 		scene.idle(20)
// 		scene.text(40, "在反应堆内部垂直放入裂变燃料组件")
// 		scene.world().showSection([3, 2, 3], Direction.DOWN)
// 		scene.world().showSection([3, 3, 3], Direction.DOWN)
// 		scene.idle(50)
// 		scene.text(40, "再在其上方放置控制棒组件")
// 		scene.world().showSection([3, 4, 3], Direction.DOWN)
// 		scene.idle(50)
// 		scene.rotateCameraY(180)
// 		scene.world().showSection([2, 2, 2, 5, 5, 5], Direction.DOWN)
// 		scene.world().moveSection(showSection, [0, -35, 0], 35)
// 		scene.idle(40)
// 		scene.addKeyframe()
// 		scene.text(40, "你也可以通过裂变反应堆逻辑适配器自动控制反应堆")
// 		scene.world().setBlocks([3, 5, 3], "mekanismgenerators:reactor_glass", true)
// 		scene.world().setBlocks([3, 5, 3], "mekanismgenerators:fission_reactor_logic_adapter", true)
// 		scene.idle(40)
// 	})
// });